### PR TITLE
Upgraded tartiflette pinning

### LINKED ISSUE #49: Tartiflette 1.0 compatibility
Not compatible with `tartiflette` `1.0`.

### PR DESCRIPTION
**Pull request by shalseban**
Upgraded `tartiflette` pinning from `<0.13` to `<1.1`

Fixes #49

### CODE REVIEW

**Comment by florimondmanca** [comment]
Thanks @shalseban! Glad to see CI passes.

Could you revert the committing of the .idea folder? You can add it to our .gitignore.

Also, I’d like to handle the version bump to 0.6 separately (there are a couple of other changes required to do it properly).

**Comment by shalseban** [comment]
Fixed. @florimondmanca

**Comment by florimondmanca** [comment]
Thanks! Will release soon.

**Comment by florimondmanca** [comment]
Unfortunately the `master` build is broken now. :( https://travis-ci.org/tartiflette/tartiflette-starlette/jobs/592720003

I'll revert the upgrade and will reopen a PR to investigate. There may have been changes recently that make the tests fail now.

**Pull request merged**
