### PR TITLE
Setup TravisCI

### LINKED ISSUE #6: Add CI pipeline

### PR DESCRIPTION
**Pull request by florimondmanca**
Fixes #6

### CODE REVIEW

**Comment by florimondmanca** [comment]
@tsunammis It seems an admin must enable `tartiflette-starlette` in their TravisCI settings before we can run pipelines. Could you check it out?

https://travis-ci.org/organizations/tartiflette/repositories

Screenshot 2019-04-21 at 15 49 05

**Comment by tsunammis** [comment]
I will fix it tonight

**Comment by tsunammis** [comment]
I activated `tartiflette-starlette` on travis ;-)

**Comment by florimondmanca** [comment]
OK, thanks @tsunammis. I can't trigger a build on a branch other than `master` so I'll merge this in now. :-)

**Pull request merged**
